### ISSUE TITLE
Filter not working with more than one integer/enum filter?

### ISSUE THREAD

**Issue by ffoxgirl** [chrisfrank/rack-reducer#9] opened 2019-06-01 08:22 UTC
Hello,

I am using Rack::Reducer to develop a Rails application where I want to filter books by various attributes. I have two attributes `:status` and `:pubtype`which are integers on the database level, but implemented as enums in my Book model. I have written both filters in exactly the same way:

```ruby
# Code in Book model
Reducer = Rack::Reducer.new(
  self.all,
  # some more attribute filters here...   
  ->(status:) { status == "" ? where("status = IFNULL(@status, status) OR (status IS NULL)") : by_status(status) },
  ->(pubtype:) { pubtype == "" ? where("pubtype = IFNULL(@pubtype, pubtype) OR (pubtype IS NULL)") : by_pubtype(pubtype) },
)
```

With this code and a corresponding form and view, `:status` is correctly filtered and only books with the desired status are shown in my view. (It is also possible to combine the filter with others like `:author`, `:genre` etc.) Trying to filter by `:pubtype`, however, produces a view with no books.

I have been trying for several hours to get both filters to work. Cutting out all the "noise" (from the other filters etc.), it _seems_ to boil down to this: **Only the integer filter that comes first works.** In the code above, only the `:status` filter works correctly. If I reverse the two lines, only the `:pubdate` filter works.

I do not experience this behavior with my string filters - I have lots of them and they all work just fine.

Tell me if you need more info and/or code snippets and I will see that I can provide them.

Looking forward to your answer!

**Comment by chrisfrank** [comment] 2019-06-04 18:31
Thanks for posting this, @ffoxgirl. I chain integer filters often, so I think the culprit is less likely to be the lambda argument type and more likely the return values of `Book::by_status` and `Book::by_pubtype`. Is it possible they're generating mutually exclusive SQL queries?

You could investigate by running something like this from your Rails console:

`Book.by_status(1).by_pubtype(2)`

That method chain should be exactly what Rack::Reducer generates under the hood at runtime. And because your Reducer is defined inside your model, you should be able to verify this in the console too:

`Book::Reducer.apply({ status: 1, pubtype: 2 })`

I'd expect both calls to return empty results, in which case the fix is probably to investigate the SQL generated by your Book methods. On the other hand, if you see results from the raw method chain but not from your Reducer, please post again here so I can investigate further! It may be helpful, in that case, to see the code for `by_status` and `by_pubdate`.

On an (I think) unrelated note, what does the `status = IFNULL(@status, status) OR (status IS NULL)` statement do? My instinct would have been to write that filter like this...

`->(status:) { status == "" ? self : by_status(status.to_i) }`

... but I haven't worked with `enum` types much, so I may have misread your intent.

**Comment by chrisfrank** [comment] 2019-06-11 22:05
@ffoxgirl were you able to get this resolved? I'd like to close the issue but not if it's still a problem for you!

**Comment by ffoxgirl** [comment] 2019-06-12 20:49
Hello @chrisfrank, thank you very much for your answer. I am sorry for not replying earlier, but I am having some personal trouble at the moment and therefore have not gotten around to trying out your suggestion. So, no, the issue is not yet solved for me.

The two scopes used in my code are very simple:

```ruby
scope :by_status, -> (status) { where(status: status) }
scope :by_pubtype, -> (pubtype) { where(pubtype: pubtype) }
```

> what does the `status = IFNULL(@status, status) OR (status IS NULL)` statement do?

Maybe I am approaching this the wrong way, but my intention is to also have those items displayed that do not have a value in their `status` (or `pubtype`) field if the respective parameter was empty. `status = IFNULL(@status, status)` is supposed to test for any integer value (since there seems to be no easy way to write an integer wildcard as there is with the `LIKE "%my_value%"` syntax with strings).

I also remember testing rather extensively through the Rails console and even the SQL console where the (I presume to be) equivalent code worked just fine, whereas it did not work with Rack::Reducer.

Sorry that I am a little out of it at the moment, but I am working on looking into this again soon.

**Comment by chrisfrank** [comment] 2019-06-20 12:15
Sending you sympathy during what sounds like a hard time, @ffoxgirl. Thank you very much for posting those scopes. I'll set up a demo Rails app that uses them and see if I can reproduce the issue you're seeing — will report back this weekend.

**Comment by chrisfrank** [comment] 2019-06-26 12:45
I set up a quick Rails app with enum filters, and it looks to me like Rack::Reducer is behaving as expected. Here's a gist with the relevant files, in case it's helpful to compare against your app:

https://gist.github.com/chrisfrank/0944b1be94363e04215dd8a64d4cab17

**Comment by chrisfrank** [comment] 2019-07-02 21:16
I'm going to close this for now, but feel free to re-open if the gist above doesn't help!

**Closed by chrisfrank** 2019-07-02 21:16 UTC
